spring:
  application:
    name: analytics
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:mysql://localhost:3306/analytics_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: analytics_user
    password: analytics_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    
  security:
    user:
      name: admin
      password: admin123

logging:
  level:
    io.manifester.analytics: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: dev
      
  datasource:
    url: jdbc:mysql://localhost:3306/analytics_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: analytics_user
    password: analytics_password
    
  jpa:
    show-sql: true
    
logging:
  level:
    io.manifester.analytics: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/analytics-dev.log

---
spring:
  config:
    activate:
      on-profile: test
      
  datasource:
    url: jdbc:mysql://localhost:3307/analytics_test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: analytics_user
    password: analytics_password
    
  jpa:
    show-sql: false
    
logging:
  level:
    io.manifester.analytics: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  file:
    name: logs/analytics-test.log

---
spring:
  config:
    activate:
      on-profile: prod
      
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/analytics_prod?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DATABASE_USERNAME:analytics_user}
    password: ${DATABASE_PASSWORD:analytics_password}
    
  jpa:
    show-sql: false
    
logging:
  level:
    io.manifester.analytics: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    root: WARN
  file:
    name: logs/analytics-prod.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
